# Generated by Django 4.1.2 on 2022-10-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutobuxSerializers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=17, max_digits=20)),
                ('name', models.TextField(max_length=200)),
                ('lastName', models.TextField(max_length=200)),
            ],
        ),
    ]
