# Generated by Django 4.1.2 on 2022-10-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuxApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutobusesSerializers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=17, max_digits=20)),
            ],
        ),
    ]
