# Generated by Django 4.1.2 on 2022-11-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuxApp', '0003_camionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea10Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('horaViaje', models.TimeField(auto_now_add=True)),
                ('fechaViaje', models.DateField()),
                ('linea', models.TextField(max_length=20)),
                ('distancia', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ayudaPersonas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('tiempoUtilizacion', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
