# Generated by Django 4.1.2 on 2022-11-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuxApp', '0004_linea10model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea10model',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
