# Generated by Django 4.1.2 on 2022-11-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuxApp', '0004_linea10model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaViaje', models.DateField()),
                ('horaViaje', models.TimeField(auto_now_add=True)),
                ('linea', models.TextField(max_length=20)),
            ],
        ),
    ]
