# Generated by Django 4.1.2 on 2022-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuxApp', '0005_alter_linea10model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea10model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
